image: openjdk:8-jdk

variables:
  ANDROID_COMPILE_SDK: "28"
  ANDROID_BUILD_TOOLS: "28.0.3"
  ANDROID_SDK_TOOLS:   "4333796"
  VARIANT:             "quickstepLawnchairDev"
  VARIANT_CAP:         "QuickstepLawnchairDev"
  FLAVOUR:             "debug"
  FLAVOUR_CAP:         "Debug"
  CHAT_ID:             "librechair"
  SECRET_BOT_TOKEN_PLACEHOLDER: "PLA CE HO LDE R"

before_script:
  - git submodule update --recursive --init
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1 screenfetch curl
  - screenfetch
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=$PATH:$PWD/android-sdk-linux/platform-tools/
  - echo "sdk.dir=$ANDROID_HOME" > local.properties
  - echo "sdk-location=$ANDROID_HOME" >> local.properties
  - chmod +x ./gradlew

stages:
  - build
  - sign
  - telegram_releases

assemble:
  stage: build
  script:
    - echo curl "https://api.telegram.org/bot${SECRET_BOT_TOKEN_PLACEHOLDER}/sendMessage?chat_id=@${CHAT_ID}&text=Continual integration triggered"
    - curl "https://api.telegram.org/bot${SECRET_BOT_TOKEN}/sendMessage?chat_id=@${CHAT_ID}&text=Continual integration triggered"
    - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-${ANDROID_SDK_TOOLS}.zip
    - unzip -d android-sdk-linux android-sdk.zip
    - echo y | android-sdk-linux/tools/bin/sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}" > /dev/null
    - echo y | android-sdk-linux/tools/bin/sdkmanager "platform-tools" > /dev/null
    - echo y | android-sdk-linux/tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}" > /dev/null
    - set +o pipefail
    - yes | android-sdk-linux/tools/bin/sdkmanager --licenses
    - set -o pipefail
    - ./gradlew assemble${VARIANT_CAP}${FLAVOUR_CAP}
  artifacts:
      untracked: true
      
signRelease:
    stage: sign
    dependencies:
     - assemble
    script:
     - mkdir outputs
     - echo "${KEYSTORE}" | base64 -d - > Librechair.jks
     - jarsigner -keystore Librechair.jks build/outputs/apk/${VARIANT}/${FLAVOUR}/apk/*.apk -storepass "${KEYSTORE_PASSWORD}" -keypass "${KEY_PASSWORD}" "${KEYSTORE_ALIAS}" --signedjar librechair-ci-signed.apk
     - mkdir outputs
     - ${ANDROID_HOME}/build-tools/${ANDROID_BUILD_TOOLS}/zipalign -v 4 librechair-ci-signed.apk outputs/librechair-ci-signed-aligned.apk
    artifacts:
       paths:
          - outputs/librechair-ci-signed-aligned.apk

sendRelease:
  stage: telegram_releases
  script:
    - apt-get install curl
    - curl "https://api.telegram.org/bot${SECRET_BOT_TOKEN}/sendMessage?chat_id=${CHAT_ID}&text=CI build completed. A new release is on it's way!"
    - curl -F chat_id=${CHAT_ID} -F document=@"outputs/librechair-ci-signed-aligned.apk" "https://api.telegram.org/bot${SECRET_BOT_TOKEN}/sendDocument"
  dependencies:
    - signRelease
